### ISSUE TITLE
Turn server

### ISSUE THREAD

**Issue by brigandimedacta** [QuickBlox/quickblox-flutter-samples#12]
Hello, i have some issues on connect chat due to network sicurity restrictions. Should i use a TURN server? how can i use this with flutter? Do quick blox has a default turn server? thanks in advance

**Comment by ghost** [comment]
@brigandimedacta Hello,

This is Nikolay from QuickBlox support.

A free QuickBlox Turn server is used by default for Video Calling. As an option, you can order a dedicated turn server.

We suggest reproducing the issue on the samples to understand if it is related to the implementation or to the connection. You may also try using a different connection/device.

Please be informed that our Cloud server is located in North Virginia, the USA. So there can be latency between your application users and the server depending on where the users are located and the Internet connection.

Unfortunately, if the issue is caused by the Internet connection, it is not possible to resolve it.

As an option, you may consider using a dedicated Enterprise instance closer to you and your main audience.
