### ISSUE TITLE
Sample Is not working with background mode in flutter sdk,

### ISSUE THREAD

**Issue by VivekBViOS** [QuickBlox/quickblox-flutter-samples#23]

**Comment by vdovbnya-qb** [comment]
Hello @VivekBViOS 
You are indeed right, the sample does not work in the background because at the moment it does not implement push notification logic. The release of this functionality is planned in the next versions. For more details on how to set up push notifications for your Flutter application, you can see our documentation at this link - https://docs.quickblox.com/docs/flutter-push-notifications
