### ISSUE TITLE
Flutter 2.5.x

### ISSUE THREAD

**Issue by adaskaliuk** [QuickBlox/quickblox-flutter-samples#4]
How about a new version of flutter?
I try to run on the new version and get many errors.

**Comment by ghost** [comment]
Hello @adaskaliuk ,

This is Nikolay from QuickBlox support.

In order to investigate the issue, we need the following points:
1. Version of QuickBlox Flutter SDK.
2. Platform (Android, iOS or both).
3. Version of the platform (e.g. Android 11, iOS 13).
4. Dart version.
5. What are the steps to reproduce on our side?
6. Please provide us with full error logs as an attachment in .txt format.

**Comment by adaskaliuk** [comment]
>> 1. Version of QuickBlox Flutter SDK.
Latest
>>2. Platform (Android, iOS or both).
Both
>>3. Version of the platform (e.g. Android 11, iOS 13).
Android 11, iOS 13
>> 4. Dart version.
Dart SDK version: 2.14.2 (stable) (Wed Sep 15 12:32:06 2021 +0200)
>> 5. What are the steps to reproduce on our side?
Check below.
flutter pub get
Running "flutter pub get" in *******...                   1,228ms
The plugin `quickblox_sdk` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated
APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by ghost** [comment]
Hello @adaskaliuk 

Thank you for the details provided.

I created an internal ticket and forwarded it to our developers.

They requested additional information. Please specify the device models you use.

In the meantime, you can use Flutter 2.3.2.

If there is any news or the developer request more information, I will let you know.

**Comment by ghost** [comment]
Hello @adaskaliuk ,

I am back with updates.

We have just released a new version of the QuickBlox Flutter SDK:
[https://pub.dev/packages/quickblox_sdk/versions/0.6.2-beta](https://pub.dev/packages/quickblox_sdk/versions/0.6.2-beta)

We added support of the latest Flutter version.

Please try updating the QuickBlox Flutter SDK and let me know if the issue is resolved.

**Comment by ghost** [comment]
Hello @adaskaliuk ,

Please let us know if you had a chance to check the new version of the QuickBlox Flutter SDK and the issue can be closed.
